espressif/idf-im-ui

.github/workflows/build_tauri.yaml, src-tauri/Cargo.lock, src-tauri/src/lib.rs, src-tauri/tauri.conf.json, src/App.vue, src/assets/espressif_logo.svg, src/assets/espressif_logo_white.svg, src/assets/main.css, src/components/GlobalProgress.vue, src/components/LoadConfig.vue, src/components/MessageDisplay.vue, src/components/SimpleSetup.vue, src/components/Welcome.vue, src/components/WizardStep.vue, src/components/wizard_steps/Complete.vue, src/components/wizard_steps/InstalationProgress.vue, src/components/wizard_steps/InstallationPathSelect.vue, src/components/wizard_steps/MirrorSelect.vue, src/components/wizard_steps/PrerequisitiesCheck.vue, src/components/wizard_steps/PythonSanitycheck.vue, src/components/wizard_steps/TargetSelect.vue, src/components/wizard_steps/VersionSelect.vue, src/router.js, src/store.js
Changed the visual appearance of the installer.
=> Eim 46 styling gui

.github/workflows/build_tauri.yaml, .github/workflows/test.yml, tests/README.md, tests/classes/USAGE.md, tests/classes/logger.class.js, tests/classes/tauriRunner.class.js, tests/package-lock.json, tests/package.json, tests/run_test.ps1, tests/run_test.sh, tests/scripts/defaultInstall.test.js, tests/scripts/expertInstall.test.js, tests/scripts/startup.test.js
This PR adds the automated tests infrastructure of the EIM GUI.
The initial test only launches the application and checks the application is running and the version printed on the page footer.
2 Additional test worflow are added:
Express installation (single click test automation process)
Expert Installation (Step by step flow using basic settings)
TODO:
Setup CI workflow
---
=> [Test] Setup autotest infrastructure

.github/workflows/build_tauri.yaml, .github/workflows/test.yml, docs/book.toml
Fixed wrong platform identification for Intel MacOs. Also, the workflow should be less repeatable now. And for non-release builds the run_id was added for easy identification of the binaries.
=> test pipeline update

src-tauri/Cargo.lock, src-tauri/Cargo.toml
This lib version bump will update the eim IDE config file to the same format as cli with the activation script with -e param outputing only the changes to the path and not full path and elf rom folder is fixed now
=> bumped lib version

.github/workflows/build_tauri.yaml
on windows the release artifacts are missing the .exe extension, this should fix it
=> Fixed release windows extension

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/lib.rs, src/components/wizard_steps/InstalationProgress.vue
=> Improved tools checksums (EIM-109)

src-tauri/src/cli/wizard.rs, src-tauri/src/gui/mod.rs, src-tauri/src/lib/idf_tools.rs, src-tauri/src/lib/mod.rs, src-tauri/src/lib/python_utils.rs, src-tauri/src/lib/utils.rs
Now the exported paths should be ok and the tolls will be not duplicate anymore.
---
=> Fixed the issue with wrong paths in the activation script

docs/src/faq.md
The problem with running the installer inside Windows Sandbox was finally resolved.
The issue is missing WebView2 Runtime
This PR just adds the information to the documentation and also serves as place for speakers to find the answer.
it really works ;-)
=> Running in Windows Sandbox

src-tauri/src/lib/idf_config.rs, src-tauri/src/lib/settings.rs
this adds the field eim_path to eim_ide.json this is breaking change as old version of eim will not parse new format of the file.
---
=> EIM-194 add eim path to eim_ide.json

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/lib/python_utils.rs
works on macos -> installed idf and build hello_world
works on windows -> installed idf and build hello_world
=> EIM-208 quoted the strings when creating venv, so they can now contain whitespace characters

src-tauri/locales/app.yml, src-tauri/src/cli/wizard.rs, src-tauri/src/gui/commands/idf_tools.rs, src-tauri/src/lib/idf_tools.rs, src-tauri/src/lib/mod.rs, src-tauri/src/lib/system_dependencies.rs, src-tauri/src/lib/utils.rs
After initial refactoring the tools installation was unified between cli and gui and logic moved to library
the tools installations are now contained in a subfolder named after tool version
globally installed tools are not installed again
=> EIM-193 tools download refactoring

src-tauri/src/lib/mod.rs
As per request, I am adding the bin/script python folder to the path, because the IDEs call `CMAKE` directly and not using the `idf.py build`.
=> added python bin path to the PATH

docs/src/cli_commands.md, src-tauri/src/cli/cli_args.rs, src-tauri/src/cli/wizard.rs, src-tauri/src/lib/settings.rs, src-tauri/src/lib/system_dependencies.rs
This makes checking for prerequisites on Linux more robust and also provides a workaround for #133, but it's not yet a fully fledged, proper solution for Fedora.
The prerequisities identification still failes on libffi-dev, libusb-1.0.0 and libssl-dev 
but if coresponding rhel libraries are installed, the check can now be skipped with 
```
./eim install --skip-prerequisites-check true
```
this way the project can be build, did not test the flashing
with the last commit the prerequisities detection works as expected. Problem should be solved
=> Eim 222 prerequisities on fedora

src-tauri/src/lib/idf_tools.rs, src-tauri/src/lib/python_utils.rs
This should solve the error with platform identification on Fedora.
=> EIM-227 stoped using python for platform identification

.github/workflows/build.yaml
This PR shoud turn off the notarisatrion of macos binaries for non release builds
=> EIM-228 only notarize release builds

src-tauri/src/lib/idf_config.rs, src-tauri/src/lib/idf_tools.rs
This should fix the permissions to ninja on POSIX systems if you have the system-wide ninja of too old, unsupported version.
=> EIM-184 fix ninja permissions

src-tauri/src/cli/cli_args.rs, src-tauri/src/cli/wizard.rs, src-tauri/src/gui/commands/installation.rs, src-tauri/src/gui/commands/settings.rs, src-tauri/src/gui/mod.rs, src-tauri/src/lib/mod.rs
In some cases, when user user `~` or `.` as path it could lead to some errors, now the path should be expanded to absolute on the application boundary, which should make the path handling more resilient.
=> Eim 239 fix path handling

docs/src/cli_commands.md, docs/src/configuration.md, docs/src/faq.md, src-tauri/bash_scripts/activate_idf_template.sh, src-tauri/powershell_scripts/idf_tools_profile_template.ps1, src-tauri/src/cli/cli_args.rs, src-tauri/src/cli/wizard.rs, src-tauri/src/gui/commands/installation.rs, src-tauri/src/lib/idf_tools.rs, src-tauri/src/lib/mod.rs, src-tauri/src/lib/settings.rs, src-tauri/src/lib/utils.rs
This PR add the 'version_name' param:
```
--version-name <VERSION_NAME>
Version name to be used for the installation. If not provided, the version will be derived from the ESP-IDF repository tag or commit hash.
```
This is mostly useful for the cases when user uses own preexisting esp-idf repository...
Because of the changes needed in activation script, the activation script now reads the version from CMAKE and is compatible with DASH and FISH shell
tested on MacOs & Windows
rebased on top of master
=> Eim 237 add name param

.github/workflows/dl_page.yaml
This workflow should publish the dl_page to [dl](https://dl.espressif.com/dl/eim/index.html) on every PR with changes to the page or the workflow and on releases ( just to be sure it's up to date).
=> Add workflow for dl page publish

.github/workflows/build.yaml, .github/workflows/build_offline_installer_archives.yaml, .github/workflows/test_cli.yml, .github/workflows/test_gui.yml, .github/workflows/test_offline.yml, tests/CLIRunner.test.js, tests/GUIRunner.test.js, tests/config.js, tests/suites/CLI-offline.json
This PR add the automated tests for IDF offline installation, using the archives build withing the run.
The workflow is set to run the test when the offline archives are built and also allow manual execution pointing to artifacts from another workflow execution (if only testing is desired).
The same approach is applied to the other test workflows to allow manual execution based on artifacts from another run, this allows quicker feedback when only changing the test workflow by using previously built artifacts.
---
=> [EIM-282] [Test] Create autotest for offline installation

dl_page/index.html
The windows section is now also corectly separated between gui and cli and the offline installer builder was separated to own tab. Also tabs now look like tabs and not buttons.
=> separated offline and online installers and builder to separat tabs and sorted out the windows gui installer

.github/workflows/build_offline_installer_archives.yaml, src-tauri/src/lib/python_utils.rs, src-tauri/src/offline_installer_builder.rs
on windows we still rely on the python 3.11 as we are installing it ourselves
on POSIX we should now support python versions "3.10", "3.11", "3.12", "3.13"
=> Eim 281 broadening python support in offline installer

.github/workflows/build_offline_installer_archives.yaml, dl_page/index.html, docs/src/offline_archive_builder.md, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/offline_installer_builder.rs
on release the pipeline should purge all existing offline installers from s3 and build offline archives for all IDF versions
manual run enables now to specify single version or all.
=> pipeline will now build offline installer archives for all versions
