espressif/idf-im-ui

README.md
docs/src/before_installing.md
docs/src/installing.md

readme improvement

---

src/components/LoadConfig.vue

EIM-119 fixed button on load config screen alignment

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src/components/wizard_steps/Complete.vue

EIM-100 save config now have defined name

---

src-tauri/src/lib.rs
src/components/wizard_steps/InstallationPathSelect.vue

EIM-111 path validation added

---

docs/src/expert_installation.md
src/components/WizardStep.vue

fix: correct typo errors

---

.github/workflows/test.yml
tests/classes/tauriRunner.class.js
tests/scripts/defaultInstall.test.js
tests/scripts/expertInstall.test.js
tests/scripts/startup.test.js

Small changes to the test scripts to match the updates to the user interface
---

[EIM-121] [test] Adjust the tests to the new UX

---

src/components/LoadConfig.vue

EIM-144 fixed hover effect of load config button

---

src/components/wizard_steps/InstalationProgress.vue

User found an issue that the instalation will look sucesssfull if the download of some tool do not even start ( because it's not present on the server). Now the installer should in that case present user with clear error message
Right now it's easy test, just run instalation of master idf version from dl.espressif mirror on windows as tool package  https://dl.espressif.com/github_assets/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-win64-x64.zip is missing so the instalation should fail.
---

EIM-147 the instalation now fails properly if download breaks

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

Release commit v0.2.0

---

src-tauri/powershell_scripts/idf_tools_profile_template.ps1
src-tauri/src/lib/mod.rs

all linebreaks should be uniified

normalized line endings

---

src/components/SimpleSetup.vue

This adds path validation before the start of the simple installation.

EIM-164 added path validation before simple setup start

---

src-tauri/src/gui/mod.rs

This fix bug where on linux the simple installation finishes but hangs and does signal to the user that it has finished.

EIM-173 fix hanging installation end on posix system

---

src/components/wizard_steps/InstalationProgress.vue

This hides the fake progressbar on POSIX systems
---

EIM-166 hide fake progress bar on POSIX systems

---

src/components/SimpleSetup.vue

The simple install now shows buttons and does not show spinner when an error during the installation ocure
---

EIM-163 error fix

---

src/components/wizard_steps/InstalationProgress.vue

Now the tools count works on POSIX too
---

Eim 170 tools count fix

---

.github/workflows/build.yaml
docs/src/faq.md

Moved build pipeline to ubuntu 22 so the resulting GUI binary should support Ubuntu 22 and newer.  Sadly for ubuntu_20 runners are already deprecated so we will not support older ubuntu that 22 with the GUI. #71 
But you can use the CLI binary which is linked staticaly.
---

supprot older ubuntu

---

src/components/SimpleSetup.vue

Spinner is never shown allongside bnuttons in simple installation

---

.github/workflows/build.yaml

fix the double zipping of artifacts

---

.github/workflows/build.yaml
src-tauri/Cargo.lock
src-tauri/Cargo.toml

release commit v0.2.1

---

src-tauri/src/lib/idf_config.rs
src-tauri/src/lib/mod.rs
src/components/SimpleSetup.vue

Fixed failing library tests and Simple setup spinner

---

src-tauri/bash_scripts/activate_idf_template.sh
src-tauri/powershell_scripts/idf_tools_profile_template.ps1
src-tauri/src/lib/mod.rs

EIM-160 return the system path to activation script

---

src-tauri/src/cli/cli_args.rs
src-tauri/src/cli/mod.rs
src-tauri/src/cli/prompts.rs
src-tauri/src/cli/wizard.rs
src-tauri/src/gui/mod.rs
src-tauri/src/lib/command_executor.rs
src-tauri/src/lib/idf_tools.rs
src-tauri/src/lib/mod.rs
src-tauri/src/lib/python_utils.rs
src-tauri/src/lib/settings.rs
src-tauri/src/lib/system_dependencies.rs
src-tauri/src/lib/utils.rs
src-tauri/src/lib/version_manager.rs
src-tauri/src/main.rs

just houskeeping cleanup of linter warnings
---

clippi cleanup

---

src-tauri/src/cli/mod.rs
src-tauri/src/gui/mod.rs
src-tauri/src/lib/command_executor.rs
src-tauri/src/lib/mod.rs
src-tauri/src/lib/system_dependencies.rs
src-tauri/src/main.rs

Fixes the prerequisites detection on Fedora Linux. Fully tested.
---

EIM-185 dependency detection on fedora fixed

---

src-tauri/src/lib/system_dependencies.rs

EIM-187 fix git detection on linux

---

src-tauri/src/lib/mod.rs
src-tauri/src/lib/settings.rs

This PR completely changes behaviour during tools installation. Now the tools are by default installed to common tools folder for all version and existing tools are not reinstalled during next installation so only the needed ones are added.
---

Eim 84 tools deduplication

---

.github/workflows/build.yaml

added installers to the build ci

---

src-tauri/src/lib/idf_config.rs

EIM-201 fix duplication record in eim_idf.json on version reinstall

---

src-tauri/src/lib/python_utils.rs

functionality of tools installing was long ago rewritten to rust part of the installer, no need to call the `idf_tool.py install` anymore
---

removed obsolete call for idf_tool.py install

---

src-tauri/src/cli/wizard.rs
src-tauri/src/gui/commands/idf_tools.rs
src-tauri/src/gui/commands/installation.rs
src-tauri/src/gui/mod.rs
src-tauri/src/lib/mod.rs
src-tauri/src/lib/python_utils.rs
src-tauri/src/lib/utils.rs

This PR removes calling the idf_tools.py from the installation process. It's mostly enabler for better paths parsing and further offline installation. 
---

reimplement idf_tools.py install-python-env

---

src-tauri/src/lib/mod.rs
src-tauri/src/lib/system_dependencies.rs
src-tauri/src/lib/utils.rs

EIM-117 added copying of openocd rules on linux

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml

release commit v0.2.2

---

src-tauri/src/cli/wizard.rs
src-tauri/src/gui/commands/installation.rs
src-tauri/src/gui/mod.rs
src-tauri/src/lib/mod.rs
src-tauri/src/lib/settings.rs
src-tauri/src/lib/utils.rs

This PR relocates all the activation scripts to a single place. It should solve possible issues with the discovery feature and make our lives little bit easier.

EIM-218 relocation of the activation scripts

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml

release commit for v0.2.6

---

docs/src/headless_usage.md

updated documentation about usage inside docker

documentation docker usage updated

---

src-tauri/bash_scripts/activate_idf_template.sh

remove double quotation marks from the activation script template

EIM-243 removed double quotation marks

---

src-tauri/src/cli/mod.rs

EIM-273 list command now displays IDF path

---

.github/workflows/test_cli.yml
.github/workflows/test_gui.yml
tests/GUIRunner.test.js
tests/config.js
tests/scripts/CLIArguments.test.js
tests/scripts/installationVerification.test.js
tests/suites/CLI-mirrors-basic.json

This PR adds Linux ARM runner and MacOS Intel runner to the autotest workflow.
This change intends to cover the basic validation of the artifacts for the mentioned architecture.
The extended tests are not valid for these architectures, at this point only basic tests are executed.
---

[EIM-265] [Test] Add test runner architectures

---

.github/workflows/build.yaml

Code signing is failing because the certificate is not present in the default keychain, so codesign cannot find it. We will import import it first before calling codesign.
---

fix(ci): address codesigning

---

.github/workflows/build_offline_installer_archives.yaml
dl_page/index.html

Offline installer added to download page

---

src-tauri/src/gui/commands/installation.rs
src/components/wizard_steps/InstalationProgress.vue

the GUI should now have better multi version install visibility:

EIM-305 fixed multiple version installation gui

---

.github/workflows/build.yaml
docs/src/cli_commands.md
docs/src/faq.md
docs/src/general_info.md
docs/src/gui_configuration.md
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/cli/cli_args.rs
src-tauri/src/cli/helpers.rs
src-tauri/src/cli/mod.rs
src-tauri/src/gui/commands/utils_commands.rs
src-tauri/src/gui/mod.rs
src-tauri/src/lib/mod.rs
src-tauri/src/lib/telemetry.rs
src/components/OfflineInstaller.vue
src/components/SimpleSetup.vue
src/components/Welcome.vue
src/components/wizard_steps/InstalationProgress.vue

ok, so it looks like this implementation actually sends events to the telemetry tracking.
Now we just need to agree upon what we actually want to measure.

EIM-54 minimal telemetry added

---

.github/workflows/test_cli.yml
.github/workflows/test_gui.yml
.github/workflows/test_offline.yml
tests/CLIRunner.test.js
tests/GUIRunner.test.js
tests/classes/CLITestRunner.class.js
tests/classes/GUITestRunner.class.js
tests/scripts/CLIArguments.test.js
tests/scripts/CLICustomInstall.test.js
tests/scripts/CLIPrerequisites.test.js
tests/scripts/CLIVersionManagement.test.js
tests/scripts/CLIWizardInstall.test.js
tests/scripts/GUICustomInstall.test.js
tests/scripts/GUISimplifiedInstall.test.js
tests/scripts/GUIStartup.test.js
tests/scripts/cleanUpRunner.test.js
tests/scripts/installationVerification.test.js
tests/scripts/prerequisitesInstall.test.js
tests/scripts/prerequisitesInstallRunner.test.js
tests/suites/CLI-extended.json
tests/suites/GUI-basic.json
tests/suites/GUI-extended.json

This PR updates the GUI automated tests to match the recent changes in the interface and navigation.
Additionally it removes the step to install python 3.11 on the offline package testing and use the default python version for Ubuntu and MacOS.
No new tests added, just changes to existing tests to math the updated interface.
Added Linux arm runner for GUI tests.
---

[EIM-297] [Test] Patch tests for new GUI

---

docs/src/SUMMARY.md
docs/src/offline_archive_builder.md
docs/src/offline_installation.md

Just publishing information about the available tool for custom offline installers.

EIM-294 offline installer builder documentation addition

---

.github/workflows/build.yaml
.github/workflows/build_offline_installer_archives.yaml
docs/src/cli_commands.md
docs/src/offline_installation.md

this should improve the release json retrieval on release builds as well as pack GUI installer to the offline archive.

another pipeline fix

---

tests/CLIRunner.test.js
tests/GUIRunner.test.js
tests/classes/GUITestRunner.class.js
tests/helper.js
tests/scripts/GUIAfterInstall.test.js
tests/scripts/GUIStartup.test.js
tests/scripts/installationVerification.test.js

Extended GUI startup test to cover more elements
This PR introduces additional assertions to the automated GUI testing. Focusing in 2 ares:
- Verify the IDF installation dashboard once the IDF install test is complete.
- Verify the links available in the page footer are available on startup.
Maintenance changes:
- Added possibility to specify "default" as IDF version to be installed, which will pick the latest released version.
- Moved helper function to an additional helper.js file.
- Added nem method on GUI test class to select multiple elements of the same type.
- Removed splash screen test step as this has different loading times and was causing ransom false negative result on the runner. Will reintroduce the test if it makes sense in the future.
---
Before submitting a Pull Request, …

[EIM-298] [Test] GUI verification after installation

---

src-tauri/src/lib/idf_versions.rs
src-tauri/src/lib/mod.rs

fix: version filter

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
yarn.lock

There is critical vulnerability in the shell tauri plugin

javascript dependency update

---

src/components/SimpleInstallatioProgressWrapper.vue
src/locales/cn.json
src/locales/en.json
src/router.js

EIM-312 unify UI of installation using config

---

.github/workflows/build_offline_installer_archives.yaml

now on release all ofline installer archives older than 24 hours will be removed

EIM-314 improve offline installer purging strategy
